### ISSUE TITLE
공통 컴포넌트를 구현한다.

### ISSUE THREAD

**Issue by yunhozz** [oduck-team/oduck-server-nestjs#16]
## 📝 개요

공통으로 쓰일 컴포넌트를 작성한다.

## ✅ TODO
- [x] `feature/16` 생성
- [x] 리뷰 단위 테스트 수정/보완
- [x] 공통 API 응답
- [x] global 예외 처리
