### ISSUE TITLE
회원 테스트, 리팩토링 및 추가 기능

### ISSUE THREAD

**Issue by FaberJoo** [oduck-team/oduck-server-nestjs#20]
## ✅ TODO
- [x] 회원 테스팅
- [x] 닉네임 변경 리팩토링
  - 자기 소개도 수정할 수 있도록 
- [x] 회원 프로필 조회 리팩토링
  - 리뷰 및 리뷰 좋아요 갯수 포함하기
- [x] 회원 소프트 딜리트
