### ISSUE TITLE
애니메이션 리뷰 도메인을 구현한다.

### ISSUE THREAD

**Issue by yunhozz** [oduck-team/oduck-server-nestjs#8]
## 📝 개요
사용자가 특정 애니메이션에 대한 한줄 리뷰 또는 장문 리뷰를 작성하는 도메인 구현

## ✅ TODO
- [x] `feature/8` 브랜치 생성
- [x] 한줄 리뷰 CRUD
- [x] 장문 리뷰 CRUD
- [x] 단위 테스트 수행
